### ISSUE TITLE
Roadmap-ish

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/PrettyPipes#79]
- [ ] Shift clicking items into filter slots
- [x] Put modules into crafting grid to reset their data
- [x] Use copper for recipes somewhere?
- [ ] Random and round robin **extraction** modifiers
- [ ] Make slot backgrounds display in red when the request button is pressed and items are missing in the crafting terminal
- [x] Pipe pressurizers should have a comparator output
- [x] Allow selecting the side of the pipe that a module applies to for extraction, filter and retrieval modules (maybe through a button that cycles and displays the name of the containers on the sides)
